config/routes.rb
Rails.application.routes.draw do
  devise_for :users
    root to: "homes#top"
    
    resources :books, only: [:new, :edit, :create, :index, :show, :update, :destroy]
    resources :users, only: [:show, :edit, :index, :create, :update]
    
    get '/home/about' => 'homes#about', as: "about"
    
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    has_one_attached :image
    belongs_to :user
    validates :title, presence: true
    validates :body, length: { minimum: 1, maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         has_many :books, dependent: :destroy
         
         has_one_attached :profile_image
         
          validates :name, length: { minimum: 2, maximum: 20 }
          validates :name, uniqueness: true
          validates :introduction, length: { maximum: 50 }
         def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
         end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
     before_action :authenticate_user!, except: [:top, :about]
    before_action :configure_permitted_parameters, if: :devise_controller?
    
     def after_sign_in_path_for(resource)
        user_path(current_user.id)
     end
     
      def after_sign_out_path_for(resource)
        root_path
      end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    def new
       @book = Book.new
    end
    
     def create
       @book = Book.new(book_params)
       @book.user_id = current_user.id
       if @book.save
          redirect_to book_path(@book.id), notice: 'You have created book successfully.'
       else       
           @books = Book.all
           render :index
       end
     end  
     
     def index
         @user = User.find(current_user.id)
         @book = Book.new
         @books = Book.all
        
     end
     
     def show
       @book = Book.find(params[:id])
       @book_new = Book.new
       @user = @book.user
     end
     
     def edit
       @book = Book.find(params[:id])
       if @book.user == current_user
           render "edit"
       else
           redirect_to books_path
       end
     end
     
     def update
       @book = Book.find(params[:id])     
       if @book.update(book_params)
           flash[:notice] = "You have updated book successfully."
       redirect_to book_path(@book.id)
       else
           render :edit
       end
     end
     
     def destroy 
        book = Book.find(params[:id])
        book.destroy
        redirect_to books_path
     end
     
     private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    def top
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user.id)
    end
   
  end
  
  def create
    @user = User.new(user_params)
    @user.user.id = current_user.id
    @user.save
    redirect_to books_path, notice: 'Signed in successfully.'
  end  
  
  def index
     @user = User.find(current_user.id)
     @users = User.all
     @book = Book.new
     
     
  end
  
  def update
     
     @user = User.find(params[:id])
     if @user.update(user_params)
        flash[:notice] = "You have updated user successfully."
        redirect_to user_path(@user)
     else
       render :edit
     end
  end
  
  private
  
  def book_params
    params.permit(:title, :body)
  end  
  
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<main>
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
<h1>Editing Book</h1>
<%= form_with model: @book do |f| %>

<div class="form-group">
<h4>Title</h4>
<%= f.text_field :title %></div>

<div class="form-group">
<h4>Opinion</h4>
<%= f.text_area :body %></div>

<div class="form-group"><%= f.submit 'Update Book' %></div>
 
<% end %>

<%= link_to "Show", book_path %>
<%= link_to "Back", books_path %>
</div>
</div>
</div> 
</main>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<main>

<%= render 'users/list', book: @book, user: current_user %>

<!--一覧ページ-->
<div class="col-md-8 offset-md-1">
<h2>Books</h2>
<table class="table table-hover table-inverse">

<thead>
    <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
        <th colspan="3"></th>
    </tr>
</thead>
<% @books.each do |book| %>
<tr>
    <td><%= link_to user_path(book.user) do %>
    <%= image_tag book.user.get_profile_image(100,100) %><% end %></td>
    <td><%= link_to book.title, book_path(book) %></td>
    <td><%= book.body %></td>
</tr>
<% end %>
</table>
</div>
</div>
</div>
</main>

app/views/books/new.html.erb
<h1>画像投稿フォーム</h1>
  <%= form_with model: @post_image do |f| %>
    <h4>画像</h4>
      <%= f.file_field :image, accept: "image/*" %>
    <h4>ショップ名</h4>
      <%= f.text_field :shop_name %>
    <h4>説明</h4>
      <%= f.text_area :caption %>
    <%= f.submit '投稿' %>
  <% end %>

app/views/books/show.html.erb
<%= render 'users/list', book: @book_new, user: @user %>
<div class = "col-md-8 offset-md-1">
<h1>Book detail</h1>
<table class="table" >
<tbody>
    
    <tr>
        <td><%= link_to user_path(@user.id) do %>
        <%= image_tag @user.get_profile_image(100,100) %>
        <% end %><br>
        <%= link_to @user.name, user_path(@user.id) %></td>
        <td><%= link_to @book.title, book_path(@book.id) %></td>

        <td><%= @book.body %></td>
        <% if @book.user == current_user %>
        <td><%= link_to edit_book_path(@book), class: "btn btn-sm btn-success edit_book_3752" do %>Edit<% end %></td>
        <td><%= link_to book_path(@book.id), method: :delete, "data-confirm" => "本当に消しますか？", class: "btn btn-danger" do %>Destroy<% end %></td>
        <% end %>
    </tr>
   
</tbody>
</table>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to<i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<main>
        <p id="notice"></p>
        <div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to<i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In<i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
        </div>
      </div>
    </div>
  </div>
</div>


      </main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
</body
 <body class="d-flex flex-column vh-100">
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand p-3" href="/">Bookers</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to user_path(current_user), class: 'nav-link text-light' do %><i class="fas fa-home"></i>Home <% end %>
            </li>
            <li class="nav-item">
              <%= link_to users_path, class: 'nav-link text-light' do %><i class="fas fa-users"></i>Users<% end %>
            </li>
            <li class="nav-item">
              <%= link_to books_path, class: 'nav-link text-light' do %><i class="fas fa-book-open"></i>Books<% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %><i class="fas fa-sign-out-alt"></i>Log out<% end %>
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to root_path, class: 'nav-link text-ligth' do %><i class="fas fa-home"></i>Home<% end %>
            </li>
            <li class="nav-item">
              <%= link_to about_path, class: 'nav-link text-light' do %><i class="fas fa-link"></i>About<% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_registration_path, class: 'nav-link text-light' do %><i class="fas fa-user-plus"></i>Sign up<% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_session_path, class: 'nav-link text-light' do %><i class="fas fa-sign-in-alt"></i>Log in <% end %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
      <p id="notice"><%= flash[:notice] %></p>
      
    <%= yield %>
    </main>
    
    <footer>
      <div class="container mt-5">
  	<div class="row">
    	<div class="mx-auto">
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
    </footer>
    
  </body>
  
</html>

 

  

app/views/users/_list.html.erb
<div class="container">
        <div class="row">
<div class="col-md-3">
<h2>User info</h2>
<%= image_tag user.get_profile_image(100, 100) %>
<table>
<tbody>
    <tr>
        <th>name</th>
        <th><%= user.name %></th>
    </tr>
    <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th>
    </tr>
</tbody>
</table>
<div class="row">
 <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block edit_user_#{user.id}" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>

</div>
<h2 class= "mt-3">New book</h2>
  <%= form_with model: book do |f| %>
 <h4>Title</h4>
  <%= f.text_field :title %>
 <h4>Opion</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Create Book' %>
 <% end %>
</div>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<main>
  <div class="containar">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
<h1>User info</h1>
<%= form_with model: @user do |f| %>
  <div class="form-group"><label for="inputName">Name</label>
  <%= f.text_field :name, autofocus: true, id:"inputName",placeholder:"名前"%></div>
  <div class="form-group"><label for="inputImage">Image</label>
  <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %></div>
  <div class="form-group"><label for="inputIntroduction">Introduction</label>
  <%= f.text_field :introduction, autofocus: true, id:"inputIntroduction" %></div>
  
  <%= f.submit "Update User" %>
  <% end %>
</div>
</div>
</div>
</main>

app/views/users/index.html.erb
<%= render 'list',  user: @user, book: @book %>
<div class="col-md-8 offset-md-1">
        
<h1>Users</h1>
<table class="table">
    <thead>
        <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
        </tr>
    </thead>
    <% @users.each do |user| %>
    <tr>
        <td><%= image_tag user.get_profile_image(100,100) %></td>
        <td><%= user.name %></td>
        <td><%= link_to "Show", user_path(user) %></td>
        <% end %>
    </tr>
</table>
</div>

app/views/users/show.html.erb
<%= render 'list', user: @user, book: @book %>

<div class="col-md-8 offset-md-1">
<h1>Books</h1>
 <table class="table table-hover table-inverse">
     <thead>
         <tr>
             <th></th>
             <th>Title</th>
             <th>Opinion</th>
             <th colspan="3"></th>
         </tr>
     </thead>
     <tbody>
         <% @books.each do |book| %>
         <tr>
             <td><%= link_to user_path(@user) do %>
              <%= image_tag book.user.get_profile_image(100,100) %></td><% end %>
             <td><%= link_to book.title, book_path(book) %></td>
             <td><%= book.body %></td>
         </tr>
             <% end %>
     </tbody>
 </table>
 </div>